-- TODO: replace icons with some digraphs
-- see :Show digraphs

local opts = {
  highlight_hovered_item = true,
  show_guides = true,
  auto_preview = false,
  position = 'left',
  relative_width = true,
  width = 15,
  auto_close = false,
  show_numbers = false,
  show_relative_numbers = false,
  show_symbol_details = true,
  preview_bg_highlight = 'Pmenu',
  autofold_depth = nil,
  auto_unfold_hover = true,
  fold_markers = { '>', '├' },
  wrap = false,
  keymaps = { -- These keymaps can be a string or a table for multiple keys
    close = {"<Esc>", "q"},
    goto_location = "<Cr>",
    focus_location = "o",
    hover_symbol = "<C-space>",
    toggle_preview = "K",
    rename_symbol = "r",
    code_actions = "a",
    fold = "z",
    unfold = "o",
    fold_all = "Z",
    unfold_all = "O",
    fold_reset = "R",
  },
  lsp_blacklist = {},
  symbol_blacklist = {},
  symbols = {
    File = {icon = "f", hl = "TSURI"},
    Module = {icon = "m", hl = "TSNamespace"},
    Namespace = {icon = "n", hl = "TSNamespace"},
    Package = {icon = "p", hl = "TSNamespace"},
    Class = {icon = "", hl = "TSType"},
    Method = {icon = "", hl = "TSMethod"},
    Property = {icon = "p", hl = "TSMethod"},
    Field = {icon = "f", hl = "TSField"},
    Constructor = {icon = "♂", hl = "TSConstructor"},
    Enum = {icon = "∃", hl = "TSType"},
    Interface = {icon = "Ѫ", hl = "TSType"},
    Function = {icon = "∫", hl = "TSFunction"},
    Variable = {icon = "V", hl = "TSConstant"},
    Constant = {icon = "C", hl = "TSConstant"},
    String = {icon = "s", hl = "TSString"},
    Number = {icon = "n", hl = "TSNumber"},
    Boolean = {icon = "b", hl = "TSBoolean"},
    Array = {icon = "A", hl = "TSConstant"},
    Object = {icon = "※", hl = "TSType"},
    Key = {icon = "κ", hl = "TSType"},
    Null = {icon = "NULL", hl = "TSType"},
    EnumMember = {icon = "", hl = "TSField"},
    Struct = {icon = "𝓢", hl = "TSType"},
    Event = {icon = "Ϟ", hl = "TSType"},
    Operator = {icon = "+", hl = "TSOperator"},
    TypeParameter = {icon = "𝙏", hl = "TSParameter"}
  }
}

require("symbols-outline").setup(opts)
